### PR TITLE
FNA port

### PR DESCRIPTION
**Pull request by flibitijibibo**
And you thought it was too late...

### CODE REVIEW

**Comment by jogleasonjr** [comment]
Hey, cool! That was fast. Thanks for doing this. Any pointers on how I can build and run? I recursive cloned FNA into the solution folder, and everything builds after that. However I get a runtime error in the `SDL2_GamePlatform` base constructor `base(game, SDL.SDL_GetPlatform())`:

<pre>
An unhandled exception of type 'System.DllNotFoundException' occurred in FNA.dll
Additional information: Unable to load DLL 'SDL2.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
</pre>

**Comment by flibitijibibo** [comment]
Grab the native libraries:

https://github.com/FNA-XNA/FNA/wiki/1:-Download-and-Update-FNA#2-download-native-libraries

In this case you only need SDL2, OpenAL Soft and MojoShader. MojoShader is in the archive noted on that page, and you can also use the SDL2.dll from that archive for now (has some DualShock fixes inside). OpenAL Soft can be found here:

http://kcat.strangesoft.net/openal.html

Also, something that might be worth considering for the FNA version: The fullscreen support is a lot less kludgy than XNA's, so you can still alt-tab out of the fullscreen mode when you need to. This could eliminate the need for direct Window.Handle interop as I wrote in the patch.

**Comment by flibitijibibo** [comment]
For reference, here's the patch that replaces the MaximizeWindow call with standard XNA stuff:

```
diff --git a/StreamLagClock/StreamLagClock/GameHost.cs b/StreamLagClock/StreamLagClock/GameHost.cs
index ed0ea57..c60894f 100644
--- a/StreamLagClock/StreamLagClock/GameHost.cs
+++ b/StreamLagClock/StreamLagClock/GameHost.cs
@@ -7,9 +7,7 @@ using Microsoft.Xna.Framework.Content;
 using Microsoft.Xna.Framework.Graphics;
 using Microsoft.Xna.Framework.Input;
 using Microsoft.Xna.Framework.Media;
-#if SDL2
-using SDL2;
-#else
+#if !SDL2
 using Forms = System.Windows.Forms;
 #endif

@@ -35,15 +33,10 @@ namespace StreamLagClock

             //maximize window
 #if SDL2
-            SDL.SDL_MaximizeWindow(Window.Handle);
-            /* Some platforms may like having these updated with the window explicitly.
-             * It depends on system window manager events though...
-             * The fun with replacing WinForms!
-             * -flibit
-             */
-            Rectangle bounds = Window.ClientBounds;
-            _graphics.PreferredBackBufferWidth = bounds.Width;
-            _graphics.PreferredBackBufferHeight = bounds.Height;
+            DisplayMode curMode = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode;
+            _graphics.IsFullScreen = true;
+            _graphics.PreferredBackBufferWidth = curMode.Width;
+            _graphics.PreferredBackBufferHeight = curMode.Height;
 #else
             var form = (Forms.Form)Forms.Form.FromHandle(Window.Handle);
             form.WindowState = Forms.FormWindowState.Maximized;
 #else
             var form = (Forms.Form)Forms.Form.FromHandle(Window.Handle);
             form.WindowState = Forms.FormWindowState.Maximized;
```

Alt-tabs just as nicely as a window!

**Comment by jogleasonjr** [comment]
Thanks for the pointers. I got it working, in Windows at least. The WinForms reference was bugging me, glad there's an alternative. I'll try to get it working on the Mac tonight. One thing I had to do was manually copy the Content folder from the bin/Debug directory from the original solution into the SDL2 one. I noticied the project reference was missing, though manually adding it back in still didn't copy those assets as part of the building chain. I'll have to look into why that is, I'm sure it's something in VS not your library. Thanks again!

**Pull request merged**
